# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

cache:
  paths:
    - .cache/pip
    - venv/

build_wheel:
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -U pip
    - pip3 install wheel
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
    expire_in: 1 week
  tags:
    - python-dinp-tscapx004r



upload_wheel:
  stage: deploy
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -U pip
    - pip3 install twine
    - echo Upload wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  tags:
    - python-dinp-tscapx004r
  when: manual


staging:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    VERSION_TAG: "1.1"
    MODEL_VERSION: "1.0"
  script:
    #- if [ -z $MODEL_NAME ]; then echo "MODEL_NAME not set"; exit 1; fi
    #- if [ -z $MODEL_VERSION ]; then echo "MODEL_VERSION not set"; exit 1; fi
    #- if [ -z $MODEL_BACKEND ]; then echo "MODEL_BACKEND not set"; exit 1; fi
    - if [ -z $INSTALL_DIR ]; then echo "INSTALL_DIR not set"; exit 1; fi
    #- if [ -z $APP_PORT ]; then echo "APP_PORT not set"; exit 1; fi
    - ipath=${INSTALL_DIR}/${VERSION_TAG}
    - echo Installation dans $ipath
    - rm -rf $ipath
    - python3 -m venv $ipath
    - source $ipath/bin/activate
    - pip3 install -U pip
    #- echo "manylinux1_compatible = True" > _manylinux.py # Pour forcer l'utilisation de manylinux1 car avec python_levenshtein_wheels, y'a un souci avec version plus récente
    - pip3 install dist/${CI_PROJECT_NAME}*.whl
    - mkdir $ipath/models
    - 'curl --insecure --header "JOB-TOKEN: ${CI_JOB_TOKEN}" ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/classificatin/${MODEL_VERSION}/classification_model.onnx -o $ipath/models/classification_model.onnx'
   # - tar xvf sivnorm_referentiel.tar -C $ipath/models
   # - echo -e "[config]\MODEL_PATH=$ipath/models\nAPP_PORT=${APP_PORT}\nBACKEND=${MODEL_BACKEND}\n" > $ipath/config.ini
    - rm -rf ${INSTALL_DIR}/current
    - ln -s $ipath ${INSTALL_DIR}/current
  tags:
    - python-dinp-tscapx004r
  
