version: '2.3'
services:
  matchvec:
    container_name: ${USER}-matchvec
    build:
      context: ./
      dockerfile: ./docker/cpu/${BACKEND}/Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
    env_file:
      - docker/env.list
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${http_proxy}
      - no_proxy=${no_proxy}
      - BACKEND=${BACKEND}
    expose:
      - ${APP_PORT}
    volumes:
      - ./:/app
      - ${MODEL_PATH}:/model
    networks:
      - isolated_nw
    labels:
      - traefik.enable=true
      - traefik.http.routers.matchvec.entrypoints=http
      - traefik.http.routers.matchvec.rule=PathPrefix(`/matchvec`) || PathPrefix(`/swaggerui`)
      - traefik.http.services.matchvec.loadbalancer.server.port=5000
    ports:
      - "5000:5000"
  redis:
    image: redis:alpine
    container_name: ${USER}-redis
    expose:
      - 6379
    networks:
      - isolated_nw


networks:
  isolated_nw:
    external:
      name: isolated_nw
