AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  IA Flash with emergency vehicles classifcation

  IA Flash app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 200
    MemorySize: 512
    Environment:
      Variables:
        BACKEND: onnx
        DETECTION_THRESHOLD: 0.4
        BASE_MODEL_PATH: /tmp
        CLASSIFICATION_MODEL: resnet18-151-refined
        CLASSIFICATION_MODEL_RPIO: resnet18-prio-refined
        DETECTION_MODEL: ssd
        DETECTION_THRESHOLD: 0.4
Resources:
  MatchvecApiPrio:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ./swagger.yaml
      BinaryMediaTypes:
         - multipart~1form-data
  MatchvecFunctionPrio:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: MatchvecFunctionPrio
      CodeUri:  ./
      Handler: lambda_function.lambda_handler_classification
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda
      Runtime: python3.6
      Policies:
        - AWSLambdaBasicExecutionRole
      Layers:
          - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:onnx:1
          - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:opencv:1
          - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:pandas:1
          - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:pillow:2
      Events:
        PostEvent:
          Type: Api
          Properties:
            RestApiId: !Ref "MatchvecApiPrio"
            Path: "/{proxy+}"
            Method: POST
        OptionEvent:
          Type: Api
          Properties:
            RestApiId: !Ref "MatchvecApiPrio"
            Path: "/{proxy+}"
            Method: OPTIONS
