AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  IA Flash

  IA Flash app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 200
    MemorySize: 512
    Environment:
      Variables:
        BACKEND: onnx
        DETECTION_THRESHOLD: 0.4
        BASE_MODEL_PATH: /tmp
        CLASSIFICATION_MODEL: resnet18-151-refined
        DETECTION_MODEL: ssd
        DETECTION_THRESHOLD: 0.4
Resources:
  MatchvecApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ./swagger.yaml
      BinaryMediaTypes:
         - multipart~1form-data
  MatchvecFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: MatchvecFunction
      CodeUri:  ./
      Handler: lambda_function.lambda_handler_classification
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda
      Runtime: python3.6
      Policies:
        - AWSLambdaBasicExecutionRole
      Layers:
          - arn:aws:lambda:eu-west-1:016363657960:layer:onnx:1
          - arn:aws:lambda:eu-west-1:016363657960:layer:opencv:1
          - arn:aws:lambda:eu-west-1:016363657960:layer:pandas:1
          - arn:aws:lambda:eu-west-1:016363657960:layer:pillow:2
      Events:
        PostEvent:
          Type: Api
          Properties:
            RestApiId: !Ref "MatchvecApi"
            Path: "/{proxy+}"
            Method: POST
        OptionEvent:
          Type: Api
          Properties:
            RestApiId: !Ref "MatchvecApi"
            Path: "/{proxy+}"
            Method: OPTIONS
