name: Python tests

on: [push]

jobs:
  build:
    name: Python test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docker/cpu/onnx/requirements.txt
          pip install -e .
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests/
        env:
          BASE_MODEL_PATH: './model'
          TORCH_HOME: './model'
          DEBUG: 1
          CLASSIFICATION_MODEL: 'resnet18-151-refined'
          CLASSIFICATION_MODEL_PRIO: 'resnet18-prio-refined'
          DETECTION_MODEL: ssd
          DETECTION_THRESHOLD: 0.4
          ANONYM_MODEL: faster_rcnn_r50_fpn_anonym
          BACKEND: 'onnx'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'
